name: bigdata2025
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.12
  - pandas
  - matplotlib
  - scikit-learn
  - openpyxl
  - opencv
  - jupyter
<<<<<<< HEAD
=======
  - flask
  - pydicom
  - scikit-image
  - plotly
  - trimesh
  - scipy
  - pillow
  - pip
  - pip:
    - SimpleITK   
>>>>>>> df2680461808889324b07107aeb19e10e20bdc5b
